baseURL = "https://iberoamerica-jena.de/"
languageCode = "de-de"
title = "Iberoamérica e.V."
theme = "ananke"

DefaultContentLanguage = "de"
[languages]
    [languages.de]
    [languages.es]
    [languages.pt]
