baseURL = "https://iberoamerica-jena.de/"
languageCode = "de-de"
title = "Iberoamérica e.V."
theme = "ibero"

DefaultContentLanguage = "de"
[languages]
    [languages.de]
        languageName = "Deutsch"
    [languages.es]
        languageName = "Español"
    [languages.pt]
        languageName = "Português"

SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "Förderung internationaler Gesinnung, der Toleranz auf allen Gebieten der Kultur und des Volkerverständigungsgedankens"
  facebook = "https://www.facebook.com/IberoamericaJena"
  twitter = ""
  instagram = "https://www.instagram.com/cincosentidos_kulturfestival/"
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
